plugins {
    id("com.android.application")
    id("kotlin-android")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

android {
    namespace = "com.yttydcs.myflowhub.clipboardnode"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }

    defaultConfig {
        applicationId = "com.yttydcs.myflowhub.clipboardnode"
        // The gomobile AAR declares minSdk 26; keep app merging honest when live Android binding is packaged.
        minSdk = maxOf(flutter.minSdkVersion, 26)
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    buildTypes {
        release {
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig = signingConfigs.getByName("debug")
        }
    }
}

flutter {
    source = "../.."
}

dependencies {
    // Generated by scripts/build_aar.*. Keep APK builds available with the explicit stub bridge when absent.
    val gomobileAar = file("libs/myflowhub.aar")
    if (gomobileAar.exists()) {
        implementation(files(gomobileAar))
    } else {
        logger.lifecycle("gomobile AAR not found; running with stub bridge: ${gomobileAar.absolutePath}")
    }
}
