plugins {
    id("com.android.application")
    id("kotlin-android")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

fun propOrEnv(propName: String, envName: String = propName): String? {
    val propValue = providers.gradleProperty(propName).orNull
    if (!propValue.isNullOrBlank()) {
        return propValue
    }
    val envValue = providers.environmentVariable(envName).orNull
    return envValue?.takeIf { it.isNotBlank() }
}

val releaseKeystorePath = propOrEnv("MYFLOWHUB_ANDROID_KEYSTORE_PATH", "ANDROID_KEYSTORE_PATH")
val releaseKeystorePassword = propOrEnv("MYFLOWHUB_ANDROID_KEYSTORE_PASSWORD", "ANDROID_KEYSTORE_PASSWORD")
val releaseKeyAlias = propOrEnv("MYFLOWHUB_ANDROID_KEY_ALIAS", "ANDROID_KEY_ALIAS")
val releaseKeyPassword = propOrEnv("MYFLOWHUB_ANDROID_KEY_PASSWORD", "ANDROID_KEY_PASSWORD")
val hasReleaseSigning =
    listOf(releaseKeystorePath, releaseKeystorePassword, releaseKeyAlias, releaseKeyPassword).all { !it.isNullOrBlank() }

android {
    namespace = "com.yttydcs.myflowhub.clipboardnode"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }

    defaultConfig {
        applicationId = "com.yttydcs.myflowhub.clipboardnode"
        // The gomobile AAR declares minSdk 26; keep app merging honest when live Android binding is packaged.
        minSdk = maxOf(flutter.minSdkVersion, 26)
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    signingConfigs {
        create("release") {
            if (hasReleaseSigning) {
                storeFile = file(releaseKeystorePath!!)
                storePassword = releaseKeystorePassword
                keyAlias = releaseKeyAlias
                keyPassword = releaseKeyPassword
            }
        }
    }

    buildTypes {
        release {
            signingConfig =
                if (hasReleaseSigning) {
                    signingConfigs.getByName("release")
                } else {
                    logger.lifecycle("Android release signing is not configured; using debug signing fallback for local/dry-run builds.")
                    signingConfigs.getByName("debug")
                }
        }
    }
}

flutter {
    source = "../.."
}

dependencies {
    // Generated by scripts/build_aar.*. Keep APK builds available with the explicit stub bridge when absent.
    val gomobileAar = file("libs/myflowhub.aar")
    if (gomobileAar.exists()) {
        implementation(files(gomobileAar))
    } else {
        logger.lifecycle("gomobile AAR not found; running with stub bridge: ${gomobileAar.absolutePath}")
    }
}
